### PR TITLE
Update ocs-chnthn-functions to use iproute2

### PR DESCRIPTION
**Pull request by notr1ch**
Fixes https://github.com/stevenshiau/clonezilla/issues/21

### CODE REVIEW

**Comment by stevenshiau** [comment]
Fixed in clonezilla 3.21.13. Thanks.

Steven

**Comment by PeterDaveHello** [comment]
Hello guys, no offense, but I wonder if the commit author(credit) should be @notr1ch as he did report a bug and also provided a valid fix? I'm just a little bit afraid of the contributors won't like to contribute to a project that will take their credits without reason. Thanks.

**Comment by stevenshiau** [comment]
@PeterDaveHello,
Thanks for mentioning this. It's definitely in the git commit log:
https://github.com/stevenshiau/clonezilla/search?q=6819b0761a74f1e3b1d97319d02bbeda6def821c&type=Commits&utf8=%E2%9C%93
"Use iproute2 to get MAC address and IP address info. Thanks to Richard
Stanway for the patch."  -> Richard Stanway is "notr1ch". Next time we'd better to mention github ID, too.
Thanks.

Steven

**Comment by PeterDaveHello** [comment]
@stevenshiau thanks for your explanation in detail, is there any plan for directly merging PRs on GitHub? Many thanks.

**Comment by stevenshiau** [comment]
@PeterDaveHello It depends. Some of them we can directly merge, but some do not. Anyway, thanks for your suggestion.

Steven

**Comment by PeterDaveHello** [comment]
Got it, thanks @stevenshiau

**Pull request closed without merging**
